name: Visual Bug Report
description: |
  Any issue that affects how UI Elements are rendered to the screen.
title: "[Visual Bug]: "
labels: ["bug (visual)", "triage"]
assignees:
  - drewhoener
body:
  - type: markdown
    attributes:
      value: |
        ## Visual Bug Report
        This report is used for reporting issues that pertain to how elements are rendered to the screen.
        If you are experiencing a crash, or another type of bug, please go and fill out that issue template instead.

        Thanks for taking the time to report an issue!
  - type: input
    id: mod-version
    attributes:
      label: Game Version
      description: What version of UIInfoSuite2 are you running?
      value: "v2.3.0-alpha-2"
    validations:
      required: true
  - type: dropdown
    id: multiplayer
    attributes:
      label: Multiplayer
      description: |
        Did this issue occur in multiplayer?
        If so, indicate whether you were the client or the host.
      options:
        - Single Player
        - Multiplayer (Host)
        - Multiplayer (Non-Host)
        - Split-Screen
      default: 0
    validations:
      required: true
  - type: input
    id: visual-settings
    attributes:
      label: Visual Settings
      description: |
        Provide your UI Zoom and UI Scale settings to help us reproduce this issue.
      placeholder: "UI Scale: 100%, Zoom: 100%"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please describe what happened, as well as what you expected to happen.
        If possible, please include images or steps to reproduce your issue!
      value: |
        ### Issue
        <!---
            Describe Your Issue, include screenshots if able
        --->

        ### Steps to Reproduce
        1. First
        2. Second
        3. Third
        4. Fourth
    validations:
      required: true
